# 訓練超參數設定
training:
  num_epochs: 20
  lr: 8e-4
  batch_size: 600
  test_size: 0.2
  random_state: 6
  weight_decay: 2e-4

scheduler:
  step_size: 50
  gamma: 0.5

model:
  input_dim: 128
  embed_dim: 128
  seq_len: 128
  num_heads: 4
  num_layers: 6
  FFN_dim: 256
  dropout: 0

paths:
  data_x: data/data_x.npy
  data_y: data/data_y.npy
  save_model: model/latest_parms.pth
  log_dir: logs/
  run_dir: runs/
